// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.WorkoutGenerateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitnessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutGenerateRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Equipment = "None",
                            FitnessLevel = "Beginner",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 2,
                            Equipment = "None",
                            FitnessLevel = "Intermediate",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 3,
                            Equipment = "None",
                            FitnessLevel = "Advanced",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 4,
                            Equipment = "TreadMill",
                            FitnessLevel = "Beginner",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 5,
                            Equipment = "TreadMill",
                            FitnessLevel = "Intermediate",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 6,
                            Equipment = "TreadMill",
                            FitnessLevel = "Advanced",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 7,
                            Equipment = "Bands",
                            FitnessLevel = "Beginner",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 8,
                            Equipment = "Bands",
                            FitnessLevel = "Intermediate",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 9,
                            Equipment = "Bands",
                            FitnessLevel = "Advanced",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 10,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Beginner",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 11,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Intermediate",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 12,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Advanced",
                            Goal = "BuildMuscles"
                        },
                        new
                        {
                            Id = 13,
                            Equipment = "None",
                            FitnessLevel = "Beginner",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 14,
                            Equipment = "None",
                            FitnessLevel = "Intermediate",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 15,
                            Equipment = "None",
                            FitnessLevel = "Advanced",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 16,
                            Equipment = "TreadMill",
                            FitnessLevel = "Beginner",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 17,
                            Equipment = "TreadMill",
                            FitnessLevel = "Intermediate",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 18,
                            Equipment = "TreadMill",
                            FitnessLevel = "Advanced",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 19,
                            Equipment = "Bands",
                            FitnessLevel = "Beginner",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 20,
                            Equipment = "Bands",
                            FitnessLevel = "Intermediate",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 21,
                            Equipment = "Bands",
                            FitnessLevel = "Advanced",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 22,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Beginner",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 23,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Intermediate",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 24,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Advanced",
                            Goal = "LoseWeight"
                        },
                        new
                        {
                            Id = 25,
                            Equipment = "None",
                            FitnessLevel = "Beginner",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 26,
                            Equipment = "None",
                            FitnessLevel = "Intermediate",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 27,
                            Equipment = "None",
                            FitnessLevel = "Advanced",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 28,
                            Equipment = "TreadMill",
                            FitnessLevel = "Beginner",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 29,
                            Equipment = "TreadMill",
                            FitnessLevel = "Intermediate",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 30,
                            Equipment = "TreadMill",
                            FitnessLevel = "Advanced",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 31,
                            Equipment = "Bands",
                            FitnessLevel = "Beginner",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 32,
                            Equipment = "Bands",
                            FitnessLevel = "Intermediate",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 33,
                            Equipment = "Bands",
                            FitnessLevel = "Advanced",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 34,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Beginner",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 35,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Intermediate",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 36,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Advanced",
                            Goal = "IncreaseEndurance"
                        },
                        new
                        {
                            Id = 37,
                            Equipment = "None",
                            FitnessLevel = "Beginner",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 38,
                            Equipment = "None",
                            FitnessLevel = "Intermediate",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 39,
                            Equipment = "None",
                            FitnessLevel = "Advanced",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 40,
                            Equipment = "TreadMill",
                            FitnessLevel = "Beginner",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 41,
                            Equipment = "TreadMill",
                            FitnessLevel = "Intermediate",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 42,
                            Equipment = "TreadMill",
                            FitnessLevel = "Advanced",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 43,
                            Equipment = "Bands",
                            FitnessLevel = "Beginner",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 44,
                            Equipment = "Bands",
                            FitnessLevel = "Intermediate",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 45,
                            Equipment = "Bands",
                            FitnessLevel = "Advanced",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 46,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Beginner",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 47,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Intermediate",
                            Goal = "ImproveFlexibility"
                        },
                        new
                        {
                            Id = 48,
                            Equipment = "WeightMachines",
                            FitnessLevel = "Advanced",
                            Goal = "ImproveFlexibility"
                        });
                });

            modelBuilder.Entity("API.Models.WorkoutGenerateResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetMuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutGenerateRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutGenerateRequestId")
                        .IsUnique();

                    b.ToTable("WorkoutGenerateResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Exercise",
                            TargetMuscleGroup = "Muscle Group",
                            WorkoutGenerateRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Exercise",
                            TargetMuscleGroup = "Muscle Group",
                            WorkoutGenerateRequestId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Exercise",
                            TargetMuscleGroup = "Muscle Group",
                            WorkoutGenerateRequestId = 3
                        },
                        new
                        {
                            Id = 4,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Treadmill Jogging",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 4
                        },
                        new
                        {
                            Id = 5,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Advanced Treadmill Sprints",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 5
                        },
                        new
                        {
                            Id = 6,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "HIIT Circuit",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 6
                        },
                        new
                        {
                            Id = 7,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Resistance Band Squats",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 7
                        },
                        new
                        {
                            Id = 8,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Resistance Band Deadlifts",
                            TargetMuscleGroup = "Back",
                            WorkoutGenerateRequestId = 8
                        },
                        new
                        {
                            Id = 9,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Advanced Band Lunges",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 9
                        },
                        new
                        {
                            Id = 10,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Leg Press",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 10
                        },
                        new
                        {
                            Id = 11,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Chest Press Machine",
                            TargetMuscleGroup = "Chest",
                            WorkoutGenerateRequestId = 11
                        },
                        new
                        {
                            Id = 12,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Pull-Down Machine",
                            TargetMuscleGroup = "Back",
                            WorkoutGenerateRequestId = 12
                        },
                        new
                        {
                            Id = 13,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Bodyweight Circuit",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 13
                        },
                        new
                        {
                            Id = 14,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Mountain Climbers",
                            TargetMuscleGroup = "Core",
                            WorkoutGenerateRequestId = 14
                        },
                        new
                        {
                            Id = 15,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Burpees",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 15
                        },
                        new
                        {
                            Id = 16,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Incline Walking",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 16
                        },
                        new
                        {
                            Id = 17,
                            ExerciseDuration = "25 minutes",
                            ExerciseName = "Treadmill Intervals",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 17
                        },
                        new
                        {
                            Id = 18,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Treadmill HIIT",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 18
                        },
                        new
                        {
                            Id = 19,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Band High Knees",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 19
                        },
                        new
                        {
                            Id = 20,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Band Side Steps",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 20
                        },
                        new
                        {
                            Id = 21,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Band Glute Kickbacks",
                            TargetMuscleGroup = "Glutes",
                            WorkoutGenerateRequestId = 21
                        },
                        new
                        {
                            Id = 22,
                            ExerciseDuration = "25 minutes",
                            ExerciseName = "Rowing Machine",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 22
                        },
                        new
                        {
                            Id = 23,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Elliptical Machine",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 23
                        },
                        new
                        {
                            Id = 24,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Cycling Machine",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 24
                        },
                        new
                        {
                            Id = 25,
                            ExerciseDuration = "10 minutes",
                            ExerciseName = "Jump Rope",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 25
                        },
                        new
                        {
                            Id = 26,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Stair Climbers",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 26
                        },
                        new
                        {
                            Id = 27,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Advanced Jump Squats",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 27
                        },
                        new
                        {
                            Id = 28,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Treadmill Walk/Jog",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 28
                        },
                        new
                        {
                            Id = 29,
                            ExerciseDuration = "25 minutes",
                            ExerciseName = "Advanced Treadmill Jogging",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 29
                        },
                        new
                        {
                            Id = 30,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "HIIT on Treadmill",
                            TargetMuscleGroup = "Cardio",
                            WorkoutGenerateRequestId = 30
                        },
                        new
                        {
                            Id = 31,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Band-Assisted Pull-ups",
                            TargetMuscleGroup = "Back",
                            WorkoutGenerateRequestId = 31
                        },
                        new
                        {
                            Id = 32,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Band Push-ups",
                            TargetMuscleGroup = "Chest",
                            WorkoutGenerateRequestId = 32
                        },
                        new
                        {
                            Id = 33,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Band Rows",
                            TargetMuscleGroup = "Back",
                            WorkoutGenerateRequestId = 33
                        },
                        new
                        {
                            Id = 34,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Weight Machines Warmup",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 34
                        },
                        new
                        {
                            Id = 35,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Advanced Free Weights",
                            TargetMuscleGroup = "Arms",
                            WorkoutGenerateRequestId = 35
                        },
                        new
                        {
                            Id = 36,
                            ExerciseDuration = "25 minutes",
                            ExerciseName = "Weight Machine Rotations",
                            TargetMuscleGroup = "Core",
                            WorkoutGenerateRequestId = 36
                        },
                        new
                        {
                            Id = 37,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Dynamic Stretches",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 37
                        },
                        new
                        {
                            Id = 38,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Yoga Beginner Flow",
                            TargetMuscleGroup = "Flexibility",
                            WorkoutGenerateRequestId = 38
                        },
                        new
                        {
                            Id = 39,
                            ExerciseDuration = "35 minutes",
                            ExerciseName = "Intermediate Yoga",
                            TargetMuscleGroup = "Flexibility",
                            WorkoutGenerateRequestId = 39
                        },
                        new
                        {
                            Id = 40,
                            ExerciseDuration = "10 minutes",
                            ExerciseName = "Treadmill Stretches",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 40
                        },
                        new
                        {
                            Id = 41,
                            ExerciseDuration = "10 minutes",
                            ExerciseName = "Treadmill Cooldown",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 41
                        },
                        new
                        {
                            Id = 42,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Treadmill Side Steps",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 42
                        },
                        new
                        {
                            Id = 43,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Band Assisted Warm-ups",
                            TargetMuscleGroup = "Legs",
                            WorkoutGenerateRequestId = 43
                        },
                        new
                        {
                            Id = 44,
                            ExerciseDuration = "15 minutes",
                            ExerciseName = "Band Cooldown",
                            TargetMuscleGroup = "Flexibility",
                            WorkoutGenerateRequestId = 44
                        },
                        new
                        {
                            Id = 45,
                            ExerciseDuration = "10 minutes",
                            ExerciseName = "Band Core Rotations",
                            TargetMuscleGroup = "Core",
                            WorkoutGenerateRequestId = 45
                        },
                        new
                        {
                            Id = 46,
                            ExerciseDuration = "20 minutes",
                            ExerciseName = "Weight Machine Warmups",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 46
                        },
                        new
                        {
                            Id = 47,
                            ExerciseDuration = "25 minutes",
                            ExerciseName = "Weight Machines Flexibility",
                            TargetMuscleGroup = "Flexibility",
                            WorkoutGenerateRequestId = 47
                        },
                        new
                        {
                            Id = 48,
                            ExerciseDuration = "30 minutes",
                            ExerciseName = "Advanced Stretching",
                            TargetMuscleGroup = "Full Body",
                            WorkoutGenerateRequestId = 48
                        });
                });

            modelBuilder.Entity("API.Models.WorkoutGenerateResponse", b =>
                {
                    b.HasOne("API.Models.WorkoutGenerateRequest", "WorkoutGenerateRequest")
                        .WithOne("WorkoutGenerateResponse")
                        .HasForeignKey("API.Models.WorkoutGenerateResponse", "WorkoutGenerateRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutGenerateRequest");
                });

            modelBuilder.Entity("API.Models.WorkoutGenerateRequest", b =>
                {
                    b.Navigation("WorkoutGenerateResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
